spring:
  profiles:
    active: local
  application:
    name: wos
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./wosdb;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

server:
  port: 8000