spring:
  profiles:
    active: local
  application:
    name: wos
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/.wos/wosdb;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;MODE=MySQL
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        hbm2ddl:
          auto: update
        show_sql: true

  h2:
    console:
      enabled: true
      path: /h2


server:
  port: 8000